export const allTopics = [
  // ── From AI Embedded.docx ──────────────────────────────────────────────────
  { title: 'A Data-Driven Precision Agriculture Framework Using Large Language Models for Crop Recommendation and Plant Disease Diagnosis', domain: 'AI / Machine Learning' },
  { title: 'A Hybrid IoT-AI Enabled Remote Patient Health Monitoring System with Virtual Doctor Assistance and Context-Aware Care', domain: 'IoT Projects' },
  { title: 'Design and Development of an Intelligent Vision-Centric Assistive Device for the Visually Impaired Using Embedded AI and Sensor Fusion', domain: 'Embedded Systems' },
  { title: 'An OpenAI-Driven Intelligent Health and Safety Assistance Framework for Real-Time Risk Prediction in Underground Coal Mining Environments', domain: 'Embedded Systems' },
  { title: 'An AI-Driven CAN-Enabled Distributed Battery and Motor Health Management System for Electric Vehicles Using IoT and OpenAI-Based Predictive Fault Diagnosis', domain: 'IoT Projects' },
  { title: 'A Generative AI-Enabled Intelligent Solar Photovoltaic Monitoring, Energy Yield Analysis, and Automated Cleaning Decision System Using IoT Sensors', domain: 'Power Electronics' },
  { title: 'An OpenAI-Assisted Intelligent Fire Safety and Evacuation Management System for Hazardous Fireworks Manufacturing Units Using IoT-Based Sensing and Predictive Suppression Control', domain: 'IoT Projects' },
  { title: 'Adaptive AI-LoRa Early-Warning System for Remote Disaster-Prone Areas', domain: 'Embedded Systems' },
  { title: 'An OpenAI-Enabled LoRaWAN Smart Sensor Tag for Predictive Cattle Behavior Analysis and Geofence-Based Alerting in Precision Livestock Farming', domain: 'IoT Projects' },
  { title: 'An OpenAI-Based Intelligent Assistive Medication Identification and Reminder System for Visually Impaired Individuals', domain: 'Bio-Medical Engineering' },

  // ── From Embedded Title Updated.docx ──────────────────────────────────────
  { title: 'Smart Safety System in Crackers Factory Using IoT and Machine Learning', domain: 'Embedded Systems' },
  { title: 'A Smart Air Pollutants Monitoring System Using ML', domain: 'IoT Projects' },
  { title: 'AI and IoT-Based Electric Vehicle Monitoring System', domain: 'IoT Projects' },
  { title: 'AI-Based Condition Monitoring of Vehicles', domain: 'AI / Machine Learning' },
  { title: 'IoT Based Coal Mine Safety and Health Monitoring System Using LoRaWAN', domain: 'IoT Projects' },
  { title: 'Recreating the Frequency Domain Properties of Seawater Channel for Underwater Optical Communication', domain: 'Embedded Systems' },
  { title: 'Application of Augmented Reality in the Field of Virtual Medical Industry Labs', domain: 'Bio-Medical Engineering' },
  { title: 'Magnetic Induction Communications on the Agriculture Field Using Wireless Underground Sensor Networks', domain: 'IoT Projects' },
  { title: 'An Artificial Intelligence-Based Bio-Medical Stroke Prediction and Analytical System Using a Machine Learning Approach', domain: 'Bio-Medical Engineering' },
  { title: 'Wireless Network-Based ICU Patient Monitoring System', domain: 'Bio-Medical Engineering' },
  { title: 'Design of a Medical Prototype Robot for Nurse Assistance', domain: 'Robotics' },
  { title: 'Designing a LoRa-Based Smart Helmet to Aid in Emergency Detection by Monitoring Bio-Signals', domain: 'Bio-Medical Engineering' },
  { title: 'A Proficient Water Monitoring System to Find Toxic Levels and Flood Predictions Using Machine Learning Techniques', domain: 'IoT Projects' },
  { title: 'Crop Prediction System by Using Machine Learning', domain: 'AI / Machine Learning' },
  { title: 'AI-Based Transformer Health Monitoring System', domain: 'Power Electronics' },
  { title: 'AI-Based Forest Fire Prediction System', domain: 'AI / Machine Learning' },
  { title: 'A LoRaWAN-Based Smart Sensor Tag for Cow Behavior Monitoring', domain: 'IoT Projects' },
  { title: 'Intelligent Farm Monitoring System Using LoRa Enabled IoT', domain: 'IoT Projects' },
  { title: 'IoT Enabled LoRa Based Power Theft Detection System', domain: 'Power Electronics' },
  { title: 'Wild Animal Detection Using a Machine Learning Approach and Alerting Using LoRa Communication', domain: 'AI / Machine Learning' },
  { title: 'LoRa Assisted Intelligent Troop Tracking and Location Monitoring System over Defense Environment', domain: 'Embedded Systems' },
  { title: 'LoRa-Based Railway Signaling System for Secondary Lines', domain: 'Embedded Systems' },
  { title: 'Integrating Electric Vehicle (EV) in Waste Management for Garbage Collection Using LoRa Technology', domain: 'IoT Projects' },
  { title: 'Smart Chair for Bio-Medical Applications Using IoT', domain: 'Bio-Medical Engineering' },
  { title: 'LoRa Transceiver for Load Monitoring and Control System in Micro Grids', domain: 'Power Electronics' },
  { title: 'Water Usage Approximation of Automated Irrigation System Using IoT and ML', domain: 'IoT Projects' },
  { title: 'Human Behavior Prediction Through Noninvasive and Privacy-Preserving Assisted Monitoring', domain: 'Bio-Medical Engineering' },
  { title: 'IoT and Machine Learning Based Approach for Fully Automated Greenhouse', domain: 'IoT Projects' },
  { title: 'IoT Based Safety Enhanced Swimming Pool with Embedded Techniques to Reduce Drowning Accidents', domain: 'IoT Projects' },
  { title: 'IoT Device for Sewage Gas Monitoring and Alert System', domain: 'IoT Projects' },
  { title: 'Pet Tracking System Using LoRa', domain: 'Embedded Systems' },
  { title: 'A Non-Invasive Glucose Monitoring SoC Based on Single Wavelength Photo Plethysmography', domain: 'Bio-Medical Engineering' },
  { title: 'A Pocket-Sized Interactive Pillbox Device', domain: 'Bio-Medical Engineering' },
  { title: 'Stress Analysis and Care Prediction System for Online Workers by IoT', domain: 'Bio-Medical Engineering' },
  { title: 'Prototype Design of Smart Home System Based on LoRa', domain: 'Embedded Systems' },
  { title: 'Intelligent Agriculture System Based on LoRa and Qt Technology', domain: 'IoT Projects' },
  { title: 'LoRa Based Smart Agriculture Network', domain: 'IoT Projects' },
  { title: 'LoRa Based Safety Smart Device for Woman Protection', domain: 'Embedded Systems' },
  { title: 'Vehicle Environment Monitoring System for Fresh Agricultural Products Distribution Based on LoRa', domain: 'IoT Projects' },
  { title: 'LoRa Wireless Sensors Network for Fruit and Vegetable Growing Application', domain: 'IoT Projects' },
  { title: 'A Design for IoT Based Smart Watering System Using LoRa', domain: 'IoT Projects' },
  { title: 'IoT Based Health Monitoring System with LoRa Communication Technology', domain: 'Bio-Medical Engineering' },
  { title: 'A Machine Learning Based Smart Irrigation System with LoRa P2P Networks', domain: 'IoT Projects' },
  { title: 'Apply LoRa Technology to Construct an Air Quality Monitoring IoT System Using Machine Learning', domain: 'IoT Projects' },
  { title: 'LoRa-Based Measurement Station for Water Quality Monitoring', domain: 'IoT Projects' },
  { title: 'LoRa (Long Range) and LoRaWAN Technology for IoT Applications in COVID-19 Pandemic', domain: 'IoT Projects' },
  { title: 'IoT and LoRa Based Substation Monitoring and Control System', domain: 'Power Electronics' },
  { title: 'Intelligent Environmental Monitoring System Based on LoRa Long Range Technology', domain: 'IoT Projects' },
  { title: 'Integrated Ambulance System', domain: 'Bio-Medical Engineering' },
  { title: 'Long-Range Body-to-Body LoRa Link at 868 MHz', domain: 'Embedded Systems' },
  { title: 'Analysis on Batik Water Waste Monitoring System Based on LoRa Communication', domain: 'IoT Projects' },
  { title: 'Performance of LoRa Gateway Based Energy Consumption and Different Frame Sizes', domain: 'Embedded Systems' },
  { title: 'Sustainable Greenhouse Practices: Comprehensive Monitoring and Control System of PV Based Greenhouse System', domain: 'IoT Projects' },
  { title: 'Innovative Agricultural Robotics: Leveraging IoT and Renewable Energy for Smart Farming', domain: 'Robotics' },
  { title: 'Smart Farming Revolution: Renewable Energy Systems for Agricultural Robots and Grass Cutters', domain: 'Robotics' },
  { title: 'Smart Sericulture Ecosystem with Fully Automated IoT Feeding Mechanism', domain: 'IoT Projects' },
  { title: 'Greenhouse Environmental Monitoring Through the Implementation of IoT and Renewable Energy Systems', domain: 'IoT Projects' },
  { title: 'IoT-Based Farm Equipment Monitoring and Management System', domain: 'IoT Projects' },
  { title: 'Energy-Efficient IoT Solutions for Sustainable Agricultural Practices', domain: 'IoT Projects' },
  { title: 'Smart Fertilization System for Sustainable Agriculture', domain: 'IoT Projects' },
  { title: 'Renewable Energy System Based Smart Irrigation System for Precision Agriculture Using IoT', domain: 'Power Electronics' },
  { title: 'IoT-Driven Pest and Disease Detection System for Crop Protection', domain: 'IoT Projects' },
  { title: 'IoT-Based Smart Wireless Charging Lanes for Electric Vehicles', domain: 'Power Electronics' },
  { title: 'IoT and Electric Vehicle Battery Management: A New Era of Monitoring and Control', domain: 'Power Electronics' },
  { title: 'Future-Ready Parking: Innovative EV Lots Using Renewable Energy and IoT Integration', domain: 'Power Electronics' },
  { title: 'IoT Based Automatic Braking Control System for EV Vehicle and Monitoring System', domain: 'Power Electronics' },
  { title: 'Embedded IoT Systems for Electric Vehicle Energy Management and Power Distribution', domain: 'Power Electronics' },
  { title: 'Smart Electric Vehicle Charging Stations: Embedded IoT for Load Balancing and Demand Response', domain: 'Power Electronics' },
  { title: 'Development of Embedded IoT Solutions for Energy Harvesting and Battery Life Extension in Electric Vehicles', domain: 'Power Electronics' },
  { title: 'Wireless Communication Protocols for Embedded IoT in Electric Vehicle Charging and Battery Management', domain: 'Power Electronics' },
  { title: 'Embedded IoT Solutions for Smart EV Charging Stations and Grid Energy Management', domain: 'Power Electronics' },
  { title: 'Smart Battery Management for Electric Vehicles IoT and PV Systems for Optimized Charging and Health Monitoring', domain: 'Power Electronics' },
  { title: 'Optimizing Battery Longevity in Electric Vehicles Using IoT-Based PV Systems for Smart Charging and Monitoring', domain: 'Power Electronics' },
  { title: 'Smart Power Conversion: IoT-Integrated Monitoring Systems for Converter Output Analysis and Management', domain: 'Power Electronics' },
  { title: 'Energy Storage and Conversion: IoT Solutions for Monitoring Inverter and Battery Output in Renewable Energy Systems', domain: 'Power Electronics' },
  { title: 'Designing IoT-Based Systems for Monitoring Converter Outputs in Renewable Energy Applications', domain: 'Power Electronics' },
  { title: 'IoT-Based Smart Health: EEG and Vital Sensor Integration', domain: 'Bio-Medical Engineering' },
  { title: 'IoT Innovations in Neonatal Care: Smart Monitoring for Baby Incubators', domain: 'Bio-Medical Engineering' },
  { title: 'Advanced Fetal Heart Rate Monitoring: Ensuring Safe Pregnancies', domain: 'Bio-Medical Engineering' },
  { title: 'Wireless Integrated Gait Analysis System for Heel Strike and Toe Off Measurement', domain: 'Bio-Medical Engineering' },
  { title: 'Smart Knee Brace Enhancing ACL Rehabilitation with Integrated Sensor Tech', domain: 'Bio-Medical Engineering' },
  { title: 'IoT-Based Methodologies for Exoskeleton Assisted Rehabilitation of the Lower Limb', domain: 'Bio-Medical Engineering' },
  { title: 'Mobile Application-Based Remote Health Monitoring of Elderly Adults Using IoT Technology', domain: 'Bio-Medical Engineering' },
  { title: 'Embedded Solutions for Structural Health Monitoring in Engineering Applications', domain: 'Embedded Systems' },
  { title: 'Real-Time Structural Health Monitoring Using Piezoelectric Sensors and Accelerometers', domain: 'Embedded Systems' },
  { title: 'Digit Pill Box Using Arduino', domain: 'Bio-Medical Engineering' },
  { title: 'Hand-Talk Assistive Technology', domain: 'Bio-Medical Engineering' },
  { title: 'IoT-Enabled Sleep Well Monitor Enhancing Health with Snore Detection and Vital Signs Monitoring', domain: 'Bio-Medical Engineering' },
  { title: 'IoT-Based Automatic Bed Vacancy Detection in Hospital', domain: 'Bio-Medical Engineering' },
  { title: 'Advanced Spirometer Based Human Respiration Diagnosis', domain: 'Bio-Medical Engineering' },
  { title: 'A Smart Tele-Healthcare System for Real-Time Health Monitoring and Remote Consultation', domain: 'Bio-Medical Engineering' },
  { title: 'E-Medicine: Health Care Monitoring System Based on IoT', domain: 'Bio-Medical Engineering' },
  { title: 'Automatic Fall Detection System for Patients with Parkinson\'s Disease', domain: 'Bio-Medical Engineering' },
  { title: 'Design and Implementation of an Interoperable IoT Based Health Monitoring System for Diabetes', domain: 'Bio-Medical Engineering' },
  { title: 'Smart Wearable Device to Prevent Accidents Caused by Medical Emergencies', domain: 'Bio-Medical Engineering' },
  { title: 'An Intelligent Baby Monitoring System Based on Raspberry Pi, IoT Sensors and Convolutional Neural Network', domain: 'Bio-Medical Engineering' },
  { title: 'Deploying IoT in Bore Well Rescue Robotics', domain: 'Robotics' },
  { title: 'Wireless Surveillance Robot with Motion Detection for Military Applications', domain: 'Robotics' },
  { title: 'Enhanced Mine Safety: A Robotic Monitoring and Alert System for Coal Operations', domain: 'Robotics' },
  { title: 'Smart Pipeline Monitoring: IoT-Enabled Design and Development of an Inspection Robot', domain: 'Robotics' },
  { title: 'AI-Based Wheeled Fire Fighting Robot with Fire-Extinguishing Ball-Shooting Turret for Forest Areas', domain: 'Robotics' },
  { title: 'Autonomous Cleaning Solutions: Design and Development of a Floor Cleaning Robot', domain: 'Robotics' },
  { title: 'Integrated Military Robotics: Wireless Multi-Functional Robot for Strategic Use', domain: 'Robotics' },
  { title: 'Smart Fire Fighter Robotics: Advanced Design and Development for Emergency Response', domain: 'Robotics' },
  { title: 'Next-Generation Industrial Robots: Enhancing Productivity and Precision', domain: 'Robotics' },
  { title: 'Robotics in Environmental Conservation: A Working Model for Plastic Waste Collection', domain: 'Robotics' },
  { title: 'Artificial Intelligence Based Human Detecting Robot for Environmental Disasters Operation', domain: 'Robotics' },
  { title: 'Smart Shopping Trolley and Customer Following Robot Using Arduino', domain: 'Robotics' },
  { title: 'Design and Development of Fire Fighter Robot Using Arduino', domain: 'Robotics' },
  { title: 'Advancing Industrial Robotics: Microcontroller-Enabled Line Follower Design', domain: 'Robotics' },
  { title: 'IoT-Driven Marine Cleaner: Revolutionizing Ocean Conservation with Smart Technology', domain: 'Robotics' },
  { title: 'Embedded IoT Systems for Robotic Healthcare Applications and Patient Monitoring', domain: 'Robotics' },
  { title: 'Hand Gesture Controlled Robot for Smart Agriculture Monitoring System', domain: 'Robotics' },
  { title: 'Artificial Intelligence-Based Human Detecting Robot for Earthquake Rescue Operation', domain: 'AI / Machine Learning' },
  { title: 'Artificial Intelligence-Driven Embedded IoT for Healthcare: Intelligent Monitoring Systems', domain: 'AI / Machine Learning' },
  { title: 'Artificial Intelligence and Embedded IoT: A Synergistic Approach to Smart Agriculture', domain: 'AI / Machine Learning' },
  { title: 'Applications of Embedded IoT in AI-Driven Traffic Management and Smart Transportation', domain: 'AI / Machine Learning' },
];
